[project]
name = "cartomancien-virtuel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.1",
    "opencv-python>=4.12.0.88",
    "pyttsx3>=2.99",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
